parameters:
#    solilokiam_front.example.class: Solilokiam\FrontBundle\Example

services:
#    solilokiam_front.example:
#        class: %solilokiam_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
